#!/usr/bin/env python
"""Run an LLM agent paired with GreedyHumanModel on an Overcooked layout.

Usage:
    python scripts/run_llm_agent.py [--model MODEL] [--layout LAYOUT] [--horizon N] [--debug]

Requires a .env file in the project root with your API key(s):
    OPENAI_API_KEY=sk-...
    ANTHROPIC_API_KEY=sk-ant-...
"""

import argparse
import time

from dotenv import load_dotenv

# Load API keys from .env before any LLM imports
load_dotenv()

from overcooked_ai_py.agents.agent import AgentPair
from overcooked_ai_py.agents.llm import LLMAgent, WorkerAgent, Planner
from overcooked_ai_py.agents.llm.observability import (
    FileRunLogger,
    LangFuseReporter,
    ObservabilityHub,
    build_run_context,
)
from overcooked_ai_py.mdp.overcooked_env import OvercookedEnv
from overcooked_ai_py.mdp.overcooked_mdp import OvercookedGridworld
from overcooked_ai_py.planning.planners import MediumLevelActionManager, MotionPlanner, NO_COUNTERS_PARAMS


def make_greedy_partner(mdp):
    """Create a GreedyHumanModel partner agent."""
    from overcooked_ai_py.agents.agent import GreedyHumanModel

    mlam = MediumLevelActionManager.from_pickle_or_compute(
        mdp, NO_COUNTERS_PARAMS, force_compute=False
    )
    return GreedyHumanModel(mlam)


def main():
    import os

    parser = argparse.ArgumentParser(description="Run LLM agent on Overcooked")
    parser.add_argument("--model", default=os.getenv("LLM_MODEL", "gpt-4o"), help="LiteLLM model name (default: from LLM_MODEL env or gpt-4o)")    
    parser.add_argument("--worker-model", default=None, help="LiteLLM model for workers (planner-worker mode only, default: same as --model)")
    parser.add_argument("--layout", default=os.getenv("LAYOUT", "cramped_room"), help="Layout name (default: from LAYOUT env or cramped_room)")    
    parser.add_argument("--horizon", type=int, default=os.getenv("HORIZON", 200), help="Episode length (default: from HORIZON env or 200)")
    parser.add_argument("--debug", action="store_true", default=os.getenv("DEBUG", "false").lower() == "true", help="Print LLM reasoning each step (default: from DEBUG env or false)")
    parser.add_argument("--visualize", action="store_true", default=os.getenv("VISUALIZE", "false").lower() == "true", help="Show real-time pygame visualization (default: from VISUALIZE env or false)")
    parser.add_argument("--fps", type=int, default=os.getenv("FPS", 2), help="Frames per second for visualization (default: from FPS env or 2)")
    parser.add_argument("--agent-type", choices=["llm", "planner-worker"], default=os.getenv("AGENT_TYPE", "llm"), help="Agent architecture: llm (LLMAgent+partner) or planner-worker (Planner+2Workers) (default: from AGENT_TYPE env or llm)")
    parser.add_argument("--replan-interval", type=int, default=os.getenv("REPLAN_INTERVAL", 5), help="Steps between replanning for planner-worker mode (default: from REPLAN_INTERVAL env or 5)")
    parser.add_argument("--run-name", default=None, help="Run identifier for observability (default: autogenerated)")
    parser.add_argument("--run-title", default="", help="Human-readable run title")
    parser.add_argument("--tags", default="", help="Comma-separated tags")
    parser.add_argument("--experiment", default="default-exp", help="Experiment label (default: default-exp)")
    parser.add_argument("--variant", default="baseline", help="Variant label (default: baseline)")
    parser.add_argument("--notes", default="", help="Free-form notes")
    args = parser.parse_args()

    # Read model, API base, and API key from environment if not provided as arguments
    model = args.model or os.getenv("LLM_MODEL") or "gpt-4o"
    worker_model = args.worker_model or os.getenv("WORKER_MODEL") or model
    api_base = os.getenv("LLM_API_BASE")
    api_key = os.getenv("LLM_API_KEY") or os.getenv("OPENAI_API_KEY")
    run_context = build_run_context(
        args,
        mode=args.agent_type,
        layout=args.layout,
        model=model,
    )
    sink = FileRunLogger(base_dir="logs/agent_runs", context=run_context)
    langfuse_enabled = bool(
        os.getenv("LANGFUSE_PUBLIC_KEY") and os.getenv("LANGFUSE_SECRET_KEY")
    )
    langfuse = LangFuseReporter(
        enabled=langfuse_enabled,
        context=run_context,
    )
    hub = ObservabilityHub(
        file_logger=sink,
        langfuse=langfuse if langfuse_enabled else None,
    )
    invoke_config = hub.build_invoke_config({})

    def safe_emit(event_type, payload, step=None, agent_role="runner"):
        try:
            hub.emit(event_type, payload, step=step, agent_role=agent_role)
        except Exception as exc:  # pragma: no cover - best-effort logging
            if args.debug:
                print(f"[observability] failed to emit {event_type}: {exc}")

    print(f"Agent type: {args.agent_type}")
    print(f"Layout: {args.layout}")
    print(f"Model: {model}")
    if args.agent_type == "planner-worker":
        print(f"Planner model: {model}")
        print(f"Worker model: {worker_model}")
        print(f"Replan interval: {args.replan_interval}")
    print(f"Run name: {run_context.run_name}")
    print(f"Horizon: {args.horizon}")
    if api_base:
        print(f"API Base: {api_base}")
    print()

    # Create MDP and environment
    mdp = OvercookedGridworld.from_layout_name(args.layout)
    env = OvercookedEnv.from_mdp(mdp, horizon=args.horizon)

    # Create agents based on agent type
    if args.agent_type == "planner-worker":
        # Planner-worker architecture: one planner coordinates two worker agents
        planner = Planner(
            model_name=model,
            replan_interval=args.replan_interval,
            debug=args.debug,
            horizon=args.horizon,
            api_base=api_base,
            api_key=api_key,
            observability=hub,
            invoke_config=invoke_config,
        )
        worker_0 = WorkerAgent(
            planner,
            "worker_0",
            model_name=worker_model,
            debug=args.debug,
            horizon=args.horizon,
            api_base=api_base,
            api_key=api_key,
            observability=hub,
            invoke_config=invoke_config,
        )
        worker_1 = WorkerAgent(
            planner,
            "worker_1",
            model_name=worker_model,
            debug=args.debug,
            horizon=args.horizon,
            api_base=api_base,
            api_key=api_key,
            observability=hub,
            invoke_config=invoke_config,
        )
        agent_pair = AgentPair(worker_0, worker_1)

        # Initialize planner after both workers registered
        env.reset()
        agent_pair.reset()
        agent_pair.set_mdp(mdp)
        planner.init(mdp, MotionPlanner(mdp))
    else:
        # Original architecture: LLMAgent paired with GreedyHumanModel
        llm_agent = LLMAgent(
            model_name=model,
            debug=args.debug,
            horizon=args.horizon,
            api_base=api_base,
            api_key=api_key,
            observability=hub,
            invoke_config=invoke_config,
        )
        partner = make_greedy_partner(mdp)
        agent_pair = AgentPair(llm_agent, partner)

        # Reset environment and agents
        env.reset()
        agent_pair.reset()
        agent_pair.set_mdp(mdp)

    # Initialize visualization if requested
    display = None
    clock = None
    if args.visualize:
        import pygame
        from overcooked_ai_py.visualization.state_visualizer import StateVisualizer

        pygame.init()
        visualizer = StateVisualizer()

        # Create display window (800x600 default size)
        display = pygame.display.set_mode((800, 600))
        pygame.display.set_caption(f"Overcooked AI - {args.layout}")
        clock = pygame.time.Clock()

        print("Visualization window opened. Close window or press ESC to exit.")

    print("Running episode...")
    start_time = time.time()
    safe_emit("run.start", {"horizon": args.horizon})
    hub.start_run()

    total_reward = 0
    done = False
    step = 0

    while not done:
        state = env.state

        # Render current state if visualizing
        if args.visualize:
            # Check for quit events
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    done = True
                    break
                if event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
                    done = True
                    break

            if done:
                break

            # Render state to display
            surf = visualizer.render_state(state, grid=mdp.terrain_mtx)

            # Scale to fit window if needed
            if surf.get_width() != display.get_width() or surf.get_height() != display.get_height():
                surf = pygame.transform.scale(surf, (display.get_width(), display.get_height()))

            display.fill((0, 0, 0))  # Clear screen
            display.blit(surf, (0, 0))
            pygame.display.flip()
            clock.tick(args.fps)

        hub.start_step(step)
        try:
            joint_action_and_infos = agent_pair.joint_action(state)
            actions = tuple(a for a, _ in joint_action_and_infos)
            infos = tuple(info for _, info in joint_action_and_infos)

            next_state, rewards, done, info = env.step(actions, infos)

            step_reward = rewards if isinstance(rewards, (int, float)) else sum(rewards)
            total_reward += step_reward

            if step_reward > 0 or args.debug:
                print(f"  Step {step}: actions={actions}, reward={step_reward}, total={total_reward}")

            step += 1
        finally:
            hub.end_step()

    # Cleanup visualization
    if args.visualize:
        pygame.quit()

    elapsed = time.time() - start_time
    safe_emit("run.end", {"total_reward": total_reward, "steps": step, "elapsed_s": elapsed})
    if langfuse_enabled:
        try:
            from langfuse import get_client

            trace_id = hub.get_trace_id() or run_context.run_id
            get_client().create_score(
                name="episode_reward",
                value=float(total_reward),
                trace_id=trace_id,
                metadata={
                    "steps": step,
                    "elapsed_s": elapsed,
                    "run_id": run_context.run_id,
                },
            )
            get_client().flush()
        except Exception:
            pass  # best-effort only
    hub.end_run({"total_reward": total_reward, "steps": step, "elapsed_s": elapsed})
    print()
    print(f"Episode finished in {step} steps ({elapsed:.1f}s)")
    print(f"Total reward: {total_reward}")
    print(f"Average time per step: {elapsed / max(step, 1):.2f}s")


if __name__ == "__main__":
    main()
